### ISSUE TITLE
`pod update` in order to use v5.0

### ISSUE THREAD

**Issue by damiancesar** [Krisiacik/ImageViewer#161]
Upon initial installation, v4.0 is installed. Just wanted to point this out, not sure if the default should be v5.0.

Also, specifying the Pod version like so...

`pod 'ImageViewer', '>= 5.0'`

and running `pod install` lead to this error: 

`None of your spec sources contain a spec satisfying the dependency: 'ImageViewer (>= 5.0)'`.

**Comment by joeljfischer** [comment]
I'm guessing you needed to update your repo with `pod repo update`
