### ISSUE TITLE
Swift 4.2 Support

### ISSUE THREAD

**Issue by dhirenthirani** [Krisiacik/ImageViewer#200]
Hey can you please make the changes required to support swift 4.2

**Comment by kubatruhlar** [comment]
There is already a PR which fails but it should not be hard to solve that issue.

**Comment by jerrygdm** [comment]
ugenlik: that commit is not swift 4.2 compatible, I got 52 issues...

**Comment by ugenlik** [comment]
@jerrygdm do you have your inhibit warnings in pod file ?

that commit works fine in my project

check this out
https://github.com/Krisiacik/ImageViewer/pull/196

**Comment by chenjie4255** [comment]
@ugenlik your commit work perfect

**Comment by RuiAAPeres** [comment]
I just merged Swift 4.2 support.

**Comment by kubatruhlar** [comment]
Great, but there is no release yet.

**Comment by Maxwell6635** [comment]
5.1.0 still not available in CocoaPods, can I know why ?

**Comment by kubatruhlar** [comment]
Probably because the podspec file is pointing to the older version.

**Comment by Maxwell6635** [comment]
Even I clear cache and all file in pod also unable to get 5.1.0 , any solution?

**Comment by xieweizhi** [comment]
@kubatruhlar 
Yep, the podspec is still pointing to the older version.

@Maxwell6635 , You can specify this pod to tag 5.1.0 in the podfile.

**Comment by Guerrix** [comment]
Any update on this?, `pod update` does not get `v5.1.0`

**Comment by Szkodniq1** [comment]
Issue with version 5.1.0 still persist, but if you need to use this library with swift 4.2, you can specify the exact merge commit made by @RuiAAPeres in your podfile:

`pod 'ImageViewer', :git => 'https://github.com/MailOnline/ImageViewer.git', :commit => 'ffe41dffb2ec0d6506d622b10099dc5e5eaeea43'`

**Comment by RuiAAPeres** [comment]
We now have Swift 5 support. Sorry for this guys. :(

**Comment by kubatruhlar** [comment]
Unfortunately version _6.0.0_ is not available via Cocoapods yet.

**Comment by RuiAAPeres** [comment]
@kubatruhlar that is correct, on the meantime could you use the alternative mentioned here: #226
