### ISSUE TITLE
swift 5.0 Support

### ISSUE THREAD

**Issue by soulCorw** [Krisiacik/ImageViewer#219]
Do you have time to add 5.0 support?

**Comment by H3ndrx** [comment]
This should be 15 min work :)

**Comment by paulsUsername** [comment]
Switft 5 would be great. Fixing everything between pod installs is not nice 😅

**Comment by BaranEm** [comment]
I would also like to welcome the support for Swift 5.

**Comment by RuiAAPeres** [comment]
Swift 5 support now available.
