### ISSUE TITLE
CocoaPods still pointing to old pod spec

### ISSUE THREAD

**Issue by Maxwell6635** [Krisiacik/ImageViewer#226]
Seems like cocoaPods dint fetch latest V6.0.0 podspecs.
https://github.com/CocoaPods/Specs/tree/master/Specs/5/b/f/ImageViewer

**Comment by granchenkooleg** [comment]
Who has a problem updating to latest V6.0.0, write:     
pod 'ImageViewer', :git => 'https://github.com/Krisiacik/ImageViewer.git'
... 
pod install

**Comment by RuiAAPeres** [comment]
@granchenkooleg The podspec should be pushed soon. Unfortunately I cannot do it myself.

**Comment by tumata** [comment]
Could someone please push the pod ? Takes a minute...

**Comment by RuiAAPeres** [comment]
Unfortunately I don't have permissions to do so. 😞

**Comment by zfoltin** [comment]
Done 🎉
