### ISSUE TITLE
EXC_BREAKPOINT 

### ISSUE THREAD

**Issue by springlo** [Krisiacik/ImageViewer#233]
```
    static var applicationWindow: UIWindow {
        return (UIApplication.shared.delegate?.window?.flatMap { $0 })!
    }
```
in Xcode 11, UIApplication.shared.delegate?.window = nil

**Comment by Visaut** [comment]
how to resolve ?

**Comment by alimirshad** [comment]
@Visaut What do you want to achieve?

**Comment by Visaut** [comment]
in Line : return (UIApplication.shared.delegate?.window?.flatMap { $0 })!
Error ->  "Fatal error: Unexpectedly found nil while unwrapping an Optional value"

use Xcode 11 , How to resolve ?

**Comment by alimirshad** [comment]
@Visaut you need to get Window from UIView. or if you need it in app delegate you need to assign the window to appdelegate window property. you can't force unwrap it like you are doing

**Comment by Visaut** [comment]
Thank you @alimirshad
